from _typeshed import Incomplete

__all__ = ['delaunay_plot_2d', 'convex_hull_plot_2d', 'voronoi_plot_2d']

def delaunay_plot_2d(tri, ax: Incomplete | None = None): ...
def convex_hull_plot_2d(hull, ax: Incomplete | None = None): ...
def voronoi_plot_2d(vor, ax: Incomplete | None = None, **kw): ...
