from _typeshed import Incomplete

def axis_slice(a, start: Incomplete | None = None, stop: Incomplete | None = None, step: Incomplete | None = None, axis: int = -1): ...
def axis_reverse(a, axis: int = -1): ...
def odd_ext(x, n, axis: int = -1): ...
def even_ext(x, n, axis: int = -1): ...
def const_ext(x, n, axis: int = -1): ...
def zero_ext(x, n, axis: int = -1): ...
