__all__ = ['spline_filter', 'gauss_spline', 'cspline1d', 'qspline1d', 'cspline1d_eval', 'qspline1d_eval']

def spline_filter(Iin, lmbda: float = 5.0): ...
def gauss_spline(x, n): ...
def cspline1d(signal, lamb: float = 0.0): ...
def qspline1d(signal, lamb: float = 0.0): ...
def cspline1d_eval(cj, newx, dx: float = 1.0, x0: int = 0): ...
def qspline1d_eval(cj, newx, dx: float = 1.0, x0: int = 0): ...
