from _typeshed import Incomplete

__all__ = ["daub", "qmf", "cascade", "morlet", "ricker", "morlet2", "cwt"]

def daub(p): ...
def qmf(hk): ...
def cascade(hk, J: int = 7): ...
def morlet(M, w: float = 5.0, s: float = 1.0, complete: bool = True): ...
def ricker(points, a): ...
def morlet2(M, s, w: int = 5): ...
def cwt(data, wavelet, widths, dtype: Incomplete | None = None, **kwargs): ...
