from ._censored_data import CensoredData as CensoredData
from ._distr_params import distcont as distcont, distdiscrete as distdiscrete
from _typeshed import Incomplete
from scipy import integrate as integrate, optimize as optimize, stats as stats
from scipy._lib import doccer as doccer
from scipy._lib._util import check_random_state as check_random_state
from scipy.special import comb as comb, entr as entr
from scipy.stats._warnings_errors import FitError as FitError

docheaders: Incomplete
docdict: Incomplete
docdict_discrete: Incomplete

class rv_frozen:
    args: Incomplete
    kwds: Incomplete
    dist: Incomplete
    def __init__(self, dist, *args, **kwds) -> None: ...
    @property
    def random_state(self): ...
    @random_state.setter
    def random_state(self, seed) -> None: ...
    def cdf(self, x): ...
    def logcdf(self, x): ...
    def ppf(self, q): ...
    def isf(self, q): ...
    def rvs(self, size: Incomplete | None = None, random_state: Incomplete | None = None): ...
    def sf(self, x): ...
    def logsf(self, x): ...
    def stats(self, moments: str = 'mv'): ...
    def median(self): ...
    def mean(self): ...
    def var(self): ...
    def std(self): ...
    def moment(self, order: Incomplete | None = None): ...
    def entropy(self): ...
    def interval(self, confidence: Incomplete | None = None): ...
    def expect(self, func: Incomplete | None = None, lb: Incomplete | None = None, ub: Incomplete | None = None, conditional: bool = False, **kwds): ...
    def support(self): ...

class rv_discrete_frozen(rv_frozen):
    def pmf(self, k): ...
    def logpmf(self, k): ...

class rv_continuous_frozen(rv_frozen):
    def pdf(self, x): ...
    def logpdf(self, x): ...

def argsreduce(cond, *args): ...

parse_arg_template: str

class rv_generic:
    def __init__(self, seed: Incomplete | None = None) -> None: ...
    @property
    def random_state(self): ...
    @random_state.setter
    def random_state(self, seed) -> None: ...
    def freeze(self, *args, **kwds): ...
    def __call__(self, *args, **kwds): ...
    def rvs(self, *args, **kwds): ...
    def stats(self, *args, **kwds): ...
    def entropy(self, *args, **kwds): ...
    def moment(self, order, *args, **kwds): ...
    def median(self, *args, **kwds): ...
    def mean(self, *args, **kwds): ...
    def var(self, *args, **kwds): ...
    def std(self, *args, **kwds): ...
    def interval(self, confidence, *args, **kwds): ...
    def support(self, *args, **kwargs): ...
    def nnlf(self, theta, x): ...

class _ShapeInfo:
    name: Incomplete
    integrality: Incomplete
    domain: Incomplete
    def __init__(self, name, integrality: bool = False, domain=..., inclusive=(True, True)) -> None: ...

class rv_continuous(rv_generic):
    badvalue: Incomplete
    name: Incomplete
    a: Incomplete
    b: Incomplete
    xtol: Incomplete
    moment_type: Incomplete
    shapes: Incomplete
    def __init__(self, momtype: int = 1, a: Incomplete | None = None, b: Incomplete | None = None, xtol: float = 1e-14, badvalue: Incomplete | None = None, name: Incomplete | None = None, longname: Incomplete | None = None, shapes: Incomplete | None = None, seed: Incomplete | None = None) -> None: ...
    def pdf(self, x, *args, **kwds): ...
    def logpdf(self, x, *args, **kwds): ...
    def cdf(self, x, *args, **kwds): ...
    def logcdf(self, x, *args, **kwds): ...
    def sf(self, x, *args, **kwds): ...
    def logsf(self, x, *args, **kwds): ...
    def ppf(self, q, *args, **kwds): ...
    def isf(self, q, *args, **kwds): ...
    def fit(self, data, *args, **kwds): ...
    def fit_loc_scale(self, data, *args): ...
    def expect(self, func: Incomplete | None = None, args=(), loc: int = 0, scale: int = 1, lb: Incomplete | None = None, ub: Incomplete | None = None, conditional: bool = False, **kwds): ...

class rv_discrete(rv_generic):
    def __new__(cls, a: int = 0, b=..., name: Incomplete | None = None, badvalue: Incomplete | None = None, moment_tol: float = 1e-08, values: Incomplete | None = None, inc: int = 1, longname: Incomplete | None = None, shapes: Incomplete | None = None, seed: Incomplete | None = None): ...
    badvalue: Incomplete
    a: Incomplete
    b: Incomplete
    moment_tol: Incomplete
    inc: Incomplete
    shapes: Incomplete
    def __init__(self, a: int = 0, b=..., name: Incomplete | None = None, badvalue: Incomplete | None = None, moment_tol: float = 1e-08, values: Incomplete | None = None, inc: int = 1, longname: Incomplete | None = None, shapes: Incomplete | None = None, seed: Incomplete | None = None) -> None: ...
    def rvs(self, *args, **kwargs): ...
    def pmf(self, k, *args, **kwds): ...
    def logpmf(self, k, *args, **kwds): ...
    def cdf(self, k, *args, **kwds): ...
    def logcdf(self, k, *args, **kwds): ...
    def sf(self, k, *args, **kwds): ...
    def logsf(self, k, *args, **kwds): ...
    def ppf(self, q, *args, **kwds): ...
    def isf(self, q, *args, **kwds): ...
    def expect(self, func: Incomplete | None = None, args=(), loc: int = 0, lb: Incomplete | None = None, ub: Incomplete | None = None, conditional: bool = False, maxcount: int = 1000, tolerance: float = 1e-10, chunksize: int = 32): ...

class rv_sample(rv_discrete):
    badvalue: Incomplete
    moment_tol: Incomplete
    inc: Incomplete
    shapes: Incomplete
    vecentropy: Incomplete
    xk: Incomplete
    pk: Incomplete
    a: Incomplete
    b: Incomplete
    qvals: Incomplete
    def __init__(self, a: int = 0, b=..., name: Incomplete | None = None, badvalue: Incomplete | None = None, moment_tol: float = 1e-08, values: Incomplete | None = None, inc: int = 1, longname: Incomplete | None = None, shapes: Incomplete | None = None, seed: Incomplete | None = None) -> None: ...
    def generic_moment(self, n): ...

def get_distribution_names(namespace_pairs, rv_base_class): ...
