from _typeshed import Incomplete

__all__ = ['_find_repeats', 'linregress', 'theilslopes', 'siegelslopes']

def linregress(x, y: Incomplete | None = None, alternative: str = 'two-sided'): ...
def theilslopes(y, x: Incomplete | None = None, alpha: float = 0.95, method: str = 'separate'): ...
def _find_repeats(arr): ...
def siegelslopes(y, x: Incomplete | None = None, method: str = 'hierarchical'): ...
