from _typeshed import Incomplete
from scipy import stats as stats

class WilcoxonDistribution:
    n: Incomplete
    def __init__(self, n) -> None: ...
    def mean(self): ...
    def cdf(self, k): ...
    def sf(self, k): ...
