def spherical_jn(n, z, derivative: bool = False): ...
def spherical_yn(n, z, derivative: bool = False): ...
def spherical_in(n, z, derivative: bool = False): ...
def spherical_kn(n, z, derivative: bool = False): ...
