from _typeshed import Incomplete

__all__ = ['diff', 'tilbert', 'itilbert', 'hilbert', 'ihilbert', 'cs_diff', 'cc_diff', 'sc_diff', 'ss_diff', 'shift']

def diff(x, order: int = 1, period: Incomplete | None = None, _cache=...): ...
def tilbert(x, h, period: Incomplete | None = None, _cache=...): ...
def itilbert(x, h, period: Incomplete | None = None, _cache=...): ...
def hilbert(x, _cache=...): ...
def ihilbert(x): ...
def cs_diff(x, a, b, period: Incomplete | None = None, _cache=...): ...
def sc_diff(x, a, b, period: Incomplete | None = None, _cache=...): ...
def ss_diff(x, a, b, period: Incomplete | None = None, _cache=...): ...
def cc_diff(x, a, b, period: Incomplete | None = None, _cache=...): ...
def shift(x, a, period: Incomplete | None = None, _cache=...): ...
