from _typeshed import Incomplete

__all__ = ['dct', 'idct', 'dst', 'idst', 'dctn', 'idctn', 'dstn', 'idstn']

def dctn(x, type: int = 2, shape: Incomplete | None = None, axes: Incomplete | None = None, norm: Incomplete | None = None, overwrite_x: bool = False): ...
def idctn(x, type: int = 2, shape: Incomplete | None = None, axes: Incomplete | None = None, norm: Incomplete | None = None, overwrite_x: bool = False): ...
def dstn(x, type: int = 2, shape: Incomplete | None = None, axes: Incomplete | None = None, norm: Incomplete | None = None, overwrite_x: bool = False): ...
def idstn(x, type: int = 2, shape: Incomplete | None = None, axes: Incomplete | None = None, norm: Incomplete | None = None, overwrite_x: bool = False): ...
def dct(x, type: int = 2, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, overwrite_x: bool = False): ...
def idct(x, type: int = 2, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, overwrite_x: bool = False): ...
def dst(x, type: int = 2, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, overwrite_x: bool = False): ...
def idst(x, type: int = 2, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, overwrite_x: bool = False): ...
