from _typeshed import Incomplete
from collections.abc import Generator

__all__ = ['set_gc_state', 'gc_state', 'assert_deallocated']

class ReferenceError(AssertionError): ...

def set_gc_state(state) -> None: ...
def gc_state(state) -> Generator[None, None, None]: ...
def assert_deallocated(func, *args, **kwargs) -> Generator[Incomplete, None, None]: ...
