__all__ = ['_deprecated']

def _deprecated(msg, stacklevel: int = 2): ...

class _DeprecationHelperStr:
    def __init__(self, content, message) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...
