from _typeshed import Incomplete

__all__ = [
    "docformat",
    "inherit_docstring_from",
    "indentcount_lines",
    "filldoc",
    "unindent_dict",
    "unindent_string",
    "extend_notes_in_docstring",
    "replace_notes_in_docstring",
    "doc_replace",
]

def docformat(docstring, docdict: Incomplete | None = None): ...
def inherit_docstring_from(cls): ...
def extend_notes_in_docstring(cls, notes): ...
def replace_notes_in_docstring(cls, notes): ...
def indentcount_lines(lines): ...
def filldoc(docdict, unindent_params: bool = True): ...
def unindent_dict(docdict): ...
def unindent_string(docstring): ...
def doc_replace(obj, oldval, newval): ...
