import _cython_3_0_10
from scipy.sparse._base import issparse as issparse
from scipy.sparse._sputils import convert_pydata_sparse_to_scipy as convert_pydata_sparse_to_scipy

__test__: dict
maximum_bipartite_matching: _cython_3_0_10.cython_function_or_method
min_weight_full_bipartite_matching: _cython_3_0_10.cython_function_or_method
