import _cython_3_0_10
from scipy.sparse._base import issparse as issparse
from scipy.sparse._csr import csr_matrix as csr_matrix
from scipy.sparse._sputils import is_pydata_spmatrix as is_pydata_spmatrix

__test__: dict
construct_dist_matrix: _cython_3_0_10.cython_function_or_method
csgraph_from_dense: _cython_3_0_10.cython_function_or_method
csgraph_from_masked: _cython_3_0_10.cython_function_or_method
csgraph_masked_from_dense: _cython_3_0_10.cython_function_or_method
csgraph_to_dense: _cython_3_0_10.cython_function_or_method
csgraph_to_masked: _cython_3_0_10.cython_function_or_method
reconstruct_path: _cython_3_0_10.cython_function_or_method
