import _cython_3_0_10
from typing import ClassVar

BLOCK_SIZE: int
__pyx_capi__: dict
__test__: dict
make_stream: _cython_3_0_10.cython_function_or_method

class GenericStream:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def all_data_read(self, *args, **kwargs): ...
    def read(self, *args, **kwargs): ...
    def seek(self, *args, **kwargs): ...
    def tell(self, *args, **kwargs): ...
    def __reduce__(self): ...
    def __reduce_cython__(self, *args, **kwargs): ...
    def __setstate_cython__(self, *args, **kwargs): ...

class ZlibInputStream(GenericStream):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def all_data_read(self, *args, **kwargs): ...
    def read(self, *args, **kwargs): ...
    def seek(self, *args, **kwargs): ...
    def tell(self, *args, **kwargs): ...
    def __reduce__(self): ...
    def __reduce_cython__(self, *args, **kwargs): ...
    def __setstate_cython__(self, *args, **kwargs): ...
