from _typeshed import Incomplete

__all__ = [
    "toeplitz",
    "circulant",
    "hankel",
    "hadamard",
    "leslie",
    "kron",
    "block_diag",
    "companion",
    "helmert",
    "hilbert",
    "invhilbert",
    "pascal",
    "invpascal",
    "dft",
    "fiedler",
    "fiedler_companion",
    "convolution_matrix",
]

def toeplitz(c, r: Incomplete | None = None): ...
def circulant(c): ...
def hankel(c, r: Incomplete | None = None): ...
def hadamard(n, dtype=...): ...
def leslie(f, s): ...
def kron(a, b): ...
def block_diag(*arrs): ...
def companion(a): ...
def helmert(n, full: bool = False): ...
def hilbert(n): ...
def invhilbert(n, exact: bool = False): ...
def pascal(n, kind: str = "symmetric", exact: bool = True): ...
def invpascal(n, kind: str = "symmetric", exact: bool = True): ...
def dft(n, scale: Incomplete | None = None): ...
def fiedler(a): ...
def fiedler_companion(a): ...
def convolution_matrix(a, n, mode: str = "full"): ...
