from _typeshed import Incomplete
from scipy._lib._array_api import array_namespace as array_namespace

def next_fast_len(target, real: bool = False) -> None: ...

next_fast_len: Incomplete

def fftfreq(n, d: float = 1.0, *, xp: Incomplete | None = None, device: Incomplete | None = None): ...
def rfftfreq(n, d: float = 1.0, *, xp: Incomplete | None = None, device: Incomplete | None = None): ...
def fftshift(x, axes: Incomplete | None = None): ...
def ifftshift(x, axes: Incomplete | None = None): ...
