from ._base import sparray
from ._compressed import _cs_matrix
from ._matrix import spmatrix
from _typeshed import Incomplete

__all__ = ['csc_array', 'csc_matrix', 'isspmatrix_csc']

class _csc_base(_cs_matrix):
    def transpose(self, axes: Incomplete | None = None, copy: bool = False): ...
    def __iter__(self): ...
    def tocsc(self, copy: bool = False): ...
    def tocsr(self, copy: bool = False): ...
    def nonzero(self): ...

def isspmatrix_csc(x): ...

class csc_array(_csc_base, sparray): ...
class csc_matrix(spmatrix, _csc_base): ...
