from _typeshed import Incomplete

__all__ = ["find", "tril", "triu"]

def find(A): ...
def tril(A, k: int = 0, format: Incomplete | None = None): ...
def triu(A, k: int = 0, format: Incomplete | None = None): ...
