import numpy as np
from _typeshed import Incomplete

__all__ = ['upcast', 'getdtype', 'getdata', 'isscalarlike', 'isintlike', 'isshape', 'issequence', 'isdense', 'ismatrix', 'get_sum_dtype']

def upcast(*args): ...
def getdtype(dtype, a: Incomplete | None = None, default: Incomplete | None = None): ...
def getdata(obj, dtype: Incomplete | None = None, copy: bool = False) -> np.ndarray: ...
def get_sum_dtype(dtype: np.dtype) -> np.dtype: ...
def isscalarlike(x) -> bool: ...
def isintlike(x) -> bool: ...
def isshape(x, nonneg: bool = False, *, allow_1d: bool = False) -> bool: ...
def issequence(t) -> bool: ...
def ismatrix(t) -> bool: ...
def isdense(x) -> bool: ...
